### PR TITLE
Add Mac application signing

### PR DESCRIPTION
**Pull request by jackpot51**

### CODE REVIEW

**Comment by jackpot51** [comment]
@ids1024 I assume we'd only want to sign and notarize release builds, right? Also to make sure PRs don't get signed

**Comment by ids1024** [comment]
Definitely make sure PRs aren't signed. Just releases makes sense. If someone is unwilling or unable to get past the warnings, it's probably best to not be running random CI builds.

**Comment by jackpot51** [comment]
It would also provide a pathway to grab our keys

**Comment by ids1024** [comment]
The `pull_request` trigger shouldn't have secrets available, though apparently Github Actions has a separate trigger that can be used if a project needs secrets when dealing with pull requests:

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
> Due to the dangers inherent to automatic processing of PRs, GitHub’s standard pull_request workflow trigger by default prevents write permissions and secrets access to the target repository. 

(Side note: first time I've seen the term "pwn request", but it's perfect.)

**Comment by jackpot51** [comment]
Now it should only sign when a release is done

**Review by ids1024 — APPROVED** [review]
Looks good. Should be fine to merge and tag a beta.

**Comment by ids1024** [comment]
Release CI running: https://github.com/pop-os/keyboard-configurator/actions/runs/828909849

**Comment by jackpot51** [comment]
Where does Show Web Page go?

**Comment by ids1024** [comment]
"Show Web Page" open https://github.com/pop-os/keyboard-configurator/releases/tag/v0.2.3-beta in the browser, since that's the page it was downloaded from.

**Pull request merged**
