### PR TITLE
Add keyboard_layout example and layouts directory

### PR DESCRIPTION
**Pull request by jackpot51**
This PR will add the keyboard remapping UI as described in https://github.com/system76/launch/issues/10

First, flash the correct firmware:
```
# Clone qmk_firmware if necessary
git clone https://github.com/system76/qmk_firmware

# Make sure it is up to date with the master branch
cd qmk_firmware
git checkout master
git pull

# Flash the firmware with the default keymap. Press Fn-Esc to reset the keyboard. 
make system76/launch_alpha_1:default:flash
```

After flashing the latest firmware, if you for any reason need to revert to the default keyboard mapping, unplug the keyboard and hold Escape while plugging it in. This will clear the keyboard mapping and restart to the bootloader. Then you can flash the keyboard again.

Next, run the configurator. Let me know if there are errors, especially when running `cargo`:

```
# Install dependencies if necessary
sudo apt-get install cargo libgtk-3-dev libhidapi-dev libusb-1.0-0-dev

# Clone keyboard-configurator if necessary
git clone https://github.com/pop-os/keyboard-configurator

# Make sure it is up to date with my feature branch
cd keyboard-configurator
git checkout keyboard-layout_nobuild
git pull

# Build and run the configurator example
./keyboard-layout.sh
```

### CODE REVIEW

**Comment by ids1024** [comment]
It seems Windows and macOS CI is failing due a build failure in `redox_hwio`.

I suppose once the keyboard backend is property abstracted, ectool should be a dependency only on Linux, if that's the only place we're supporting EC keyboard configuration (or it can be updated as necessary to work with some kind of Windows driver,  if we're doing that).

**Comment by ids1024** [comment]
Is the contents of `layouts/` here generated by some script(s)? Seeing all that added makes me wonder if it should be generated in a build script. Though I guess if this generally doesn't change except for the addition of new models, it doesn't matter much.

**Comment by jackpot51** [comment]
@ids1024 layouts/ is mostly generated.

**Comment by leviport** [comment]
A bit of an issue I noticed right away: the window is too tall to completely fit on a 1080p display. It's also not clear that there is more below what I am seeing, and if I don't drag the window up, I may not discover that Controls, LED Controls, or Layer Keys existed.

**Comment by jackpot51** [comment]
Ok, I will try to fix the mapping. We will need adjustments either to button and text size or to the layout to fit it on a 1080p screen

**Comment by leviport** [comment]
Would it be possible to make the button section below the layout scrollable? 1080p is kinda the default smallest for our products, but I feel like we should try to accommodate smaller resolutions as much as we can.

**Comment by jackpot51** [comment]
It's definitely possible

**Comment by jackpot51** [comment]
Latest commit will make the window scroll

**Comment by leviport** [comment]
This is looking good. I just mapped and remapped every key on layer 0 and it worked as expected. I can make the window pretty small and it's still relatively usable. It gets annoying if I make the width too narrow, but it is still usable.

**Comment by maria-komarova** [comment]
Probably no frame. It might add more clutter potentially. So better nail down the spacing and headers.

**Comment by ids1024** [comment]
Some keys look a bit funny as they get wider to accommodate longer labels. Not sure how best to deal with that, but it could probably be improved a bit.

Screenshot from 2020-10-01 09-31-16

Functionally, this seems to be working fairly well.

**Comment by jackpot51** [comment]
We are going to probably rename Caps Lock to Caps and Backspace to Bksp to match what launch has

**Comment by jackpot51** [comment]
LED items could be made two lines

**Comment by ids1024** [comment]
`keyboard_layout.rs` should have `#![windows_subsystem = "windows"]` at the top of the file, so Windows doesn't open a terminal window when it's run.

(It can still be run from a terminal manually to see the output.)

**Comment by jackpot51** [comment]
Rebased on master again

**Review by ids1024 — APPROVED** [review]

**Pull request merged**
