### PR TITLE
feat: Add launch_heavy_1

### PR DESCRIPTION
**Pull request by ids1024**
In theory should work, though resetting layout errors due to default LED configuration not being correctly populated.

Launch Heavy should also have its own USB product ID.

### CODE REVIEW

**Comment by ids1024** [comment]
Updated to match latest version of `launch_heavy_1` QMK branch.

**Comment by ids1024** [comment]
Ah, the unit test failure seems to be that `physical.json` (the json file from http://www.keyboard-layout-editor.com) doesn't match the keymap in the expected way.

**Review by leviport — DISMISSED** [review]
Looking good with https://github.com/system76/qmk_firmware/pull/30/

**Comment by leviport** [comment]
I believe the [bug I found](https://github.com/system76/qmk_firmware/pull/30#issuecomment-1294173387) is in the firmware, rather than the configurator, but we should probably get to the bottom of it before we merge either PR.

**Comment by leviport** [comment]
I'm seeing a potential problem with LEDs being saved on Heavy after the keyboard is unplugged. I can change LEDs to whatever I want, but unplugging the keyboard and plugging it back in always reverts to the default Spacetime LEDs on the first layer, and Bound Keys on the rest of the layers. Brock is looking into whether this is firmware-related or configurator-related.

**Comment by ids1024** [comment]
> but unplugging the keyboard and plugging it back in always reverts to the default Spacetime LEDs on the first layer

To avoid EEPROM wear (color can change many times a second moving around the color wheel) LED settings aren't saved immediately. You have to wait 10s or close the Configurator.

If that's not the issue, I guess see if the `led_save` command is being handled correctly by the firmware. (And it's loading the saved configuration on start.)

**Comment by leviport** [comment]
I think that's probably not the issue. I was definitely aware of that mechanism, so I tried waiting a while and closing the configurator before unplugging Heavy, and the same thing would happen every time. Plus, I was testing the same thing on launch_1 and launch_lite_1 to make sure it wasn't just me unplugging it too quickly, and they were holding the LED settings as expected. Brock is taking a look though, so I'm sure he'll find something soon.

**Comment by 13r0ck** [comment]
Ya this is a problem with the heavy firmware and led_save, specifically [system76_ec_rgb_eeprom](https://github.com/system76/qmk_firmware/blob/master/keyboards/system76/system76_ec.c#L199). Something is off with how we are writing to the eeprom. I will continue to look at it tomorrow

**Comment by 13r0ck** [comment]
> I'm seeing a potential problem with LEDs being saved on Heavy after the keyboard is unplugged. I can change LEDs to whatever I want, but unplugging the keyboard and plugging it back in always reverts to the default Spacetime LEDs on the first layer, and Bound Keys on the rest of the layers. Brock is looking into whether this is firmware-related or configurator-related

Fixed in [3fd50ece8b90735170ac10c6f70bcad11e20c663](https://github.com/system76/qmk_firmware/pull/30/commits/3fd50ece8b90735170ac10c6f70bcad11e20c663)

Save failed because the configured EEPROM size was too small for required size to save.

**Pull request merged**
