### PR TITLE
Brazilian Portuguese translation for the 'Selma Test' section update

### PR DESCRIPTION
**Pull request by lucassfank**

### CODE REVIEW

**Comment by lucassfank** [comment]
Hi! Not sure if this is the way to do it (working in the same branch of the last pull request already in master), but the objective is to pull the commit 506f8f8.

**Comment by mmstick** [comment]
You would generally switch to the master branch and create a new branch from that.

**Comment by lucassfank** [comment]
Ok, great! Thanks for the tip. So should I do that or is this one fine?

**Review by jacobgkau — APPROVED** [review]
Thank you for the update! Based on the diff, this PR looks valid to me. I've tested this branch with an English user account and a Portuguese user account, and the translation is showing up properly. This PR should be squashed automatically when merged (or it looks like rebasing is also an option.)

**Pull request merged**
