### PR TITLE
fix: Use correct scancodes for LED Controls on Launch

### PR DESCRIPTION
**Pull request by ids1024**
It looks like these were broken in https://github.com/pop-os/keyboard-configurator/pull/164.

The `BACKLIGHT_` scancodes in QMK are different, and don't do anything since the `rules.mk` files for our keyboards have `BACKLIGHT_ENABLE = no`.

### CODE REVIEW

**Review by 13r0ck — APPROVED** [review]

**Comment by leviport** [comment]
Is this another case where I need to delete some version file in my QMK directory? Here is what I'm seeing with currently released configurator:

and here's what I'm seeing on this branch:

**Comment by ids1024** [comment]
Are the LED keys on they keyboard working correctly? That suggests they are mapped to `BACKLIGHT_*`. Which would have been the behavior if you used `Reset Layout` in the Configurator before this change. But then they shouldn't actually do anything mapped that way.

`Reset Layout` in either version of the Configurator will revert the layout to the scancodes that version thinks are correct.

**Comment by leviport** [comment]
Ah yep, that was the problem. Loading a map, default or otherwise, with the currently released configurator has the right text, but non-functioning LED controls. Loading a map with this branch fixes both. I'll test a few more models, now that I understand the breakage better.

**Comment by ids1024** [comment]
Yep. The reason I noticed an issue is when I was trying to adjust the brightness of my keyboard and the key for it was doing nothing.

**Review by leviport — APPROVED** [review]
Works great on launch_1, launch_2, launch_lite_1, and launch_heavy_1

**Pull request merged**
