### PR TITLE
Version 1.3.12, with arm64 macOS build

### PR DESCRIPTION
**Pull request by ids1024**
The macOS arm64 build here seems to work on an M1 mac, except for signing (is Apple silicon more restrictive about this?). The ad-hoc signature it is signed with seemed to work on the CI signature, but I had to resign locally to run on my system.

This PR doesn't change the Configurator itself or the Debian packaging, except for the version bump. The other changes are to CI and the macOS scripts.

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by jacobgkau** [comment]
Putting these in a comment so I can grab them from the test machines without logging in:

macOS build: [keyboard-configurator-macos-arm64-331de4f3a735f332557a647590784731cbb63985.zip](https://github.com/user-attachments/files/16534301/keyboard-configurator-macos-arm64-331de4f3a735f332557a647590784731cbb63985.zip)
Windows build: 
[keyboard-configurator-mingw32-331de4f3a735f332557a647590784731cbb63985.zip](https://github.com/user-attachments/files/16534303/keyboard-configurator-mingw32-331de4f3a735f332557a647590784731cbb63985.zip)

**Comment by jacobgkau** [comment]
I'm getting an error trying to run this on an M1 Mac Mini with macOS 13.3 Ventura:

Screenshot 2024-08-07 at 3 40 13 PM

Here's the crash reporter's output (I did not submit it to Apple): [macOS Crash Report.txt](https://github.com/user-attachments/files/16534450/macOS.Crash.Report.txt)

The currently released version 1.3.10 still works on this machine.

Should I try upgrading to macOS 14 Sonoma, or are we still expecting this to work on Ventura?

**Comment by ids1024** [comment]
If you click "report" and "more information" it should show that this is a signing issue. I don't recall this being an issue, so maybe Apple is stricter on arm64 (or on the latest macOS), or maybe there was some setting I had enabled to test previously.

The binary ran on CI. It seemed to fail when I tried on an M1 Mac Mini, I guess since it was signed on a different system. Running a couple commands to resign binaries made it work.

So *hopefully* it will work in the tagged release, where we have CI sign it with a release key.

**Comment by jacobgkau** [comment]
> If you click "report" and "more information" it should show that this is a signing issue.

Clicking those got me the log file I posted. I guess that log does say "Code Signature Invalid." Ok, I'll move on from that and check it again once it's merged.

**Review by jacobgkau — APPROVED** [review]
This is working to configure a Launch on Windows, and to configure the internal keyboard on lemp13 (both deb and AppImage).

**Pull request merged**
