### PR TITLE
Scancodes

### PR DESCRIPTION
**Pull request by 13r0ck**
for system76/qmk_firmware#34

### CODE REVIEW

**Comment by ids1024** [comment]
So this will cause issues with boards on the older firmware, where `FN` has a different value? This is a problem if firmware updates aren't automatic, and we don't have firmware updates integrated for Window and macOS.

**Comment by 13r0ck** [comment]
Doesn't seem that bad to me, the buttons still work, just users with (eventually) outdated firmware will not have labeled GUI buttons.
The keyboard-configurator code here is just a simple map, so there shoundnt be an issue if we have two "FN" values. That would support both

**Comment by ids1024** [comment]
Also if `FN` has changed the other `LAYER_ACCCESS_*` bindings probably have too. And possibly others.

> users with (eventually) outdated firmware will not have labeled GUI buttons, until they update.

Not just that. Mapping a key to "Fn" will set the wrong binding, and "Reset Layout" will set the key to the wrong binding. Breaking use of the "Fn" key with no obvious way to fix it, which is a fairly serious issue.

**Comment by ids1024** [comment]
I haven't tried this change or the firmware update, but `keymap.json` defines the keycode values that are used in `layouts/system76/launch_1/default.json` and `layouts/picker.json` for the default layout and picker, so it should impact those. This mapping isn't just about labels.

**Comment by 13r0ck** [comment]
Just checked with levi, this works, but other keys are broken too. I think we should look into the `info.json` files that upstream (and via use), rather than the scancode map

**Comment by 13r0ck** [comment]
There is some way that [Via](https://www.caniusevia.com/) knows without needing scancode config

**Comment by ids1024** [comment]
Running this branch with older firmware, and using "Reset Layout", `Fn` still transitions to layer 1, but it's not momentary, and is stuck on that until I unplug it and plug it back in.

**Comment by leviport** [comment]
Yeah there are definitely some problems with this fix. I think Brock is right about trying to identify keys the way VIA does it. This could also make VIA compatibility more realistic, which could be a nice addition.

**Comment by 13r0ck** [comment]
Unfortunately, the via implementation will be too large for now. So this doesn't do that. eventhough I would like to in the future. 
This currently just maps firmware version to a different scancode to name map. This fixes the other scancodes that I didn't notice before,  as well as not breaking compatibility for non-updated keyboards.

I still need to do cleanup tomorrow morning. Just pushing to here for now, just in case my dog eats my laptop.

**Comment by 13r0ck** [comment]
@ids1024 @leviport this is ready for review now.

**Comment by ids1024** [comment]
This has changed `BACKSPACE` to `BKSP`. This makes the label defined in `picker.json` no longer match. We'll also want to keep the name unchanged to keep exported layouts compatible.

On older firmware, this still doesn't seem to show the FN key mapped properly.

**Comment by 13r0ck** [comment]
> This has changed BACKSPACE to BKSP.

On old or new firmware?

> On older firmware, this still doesn't seem to show the FN key mapped properly.

You will have to re-flash firmware on your keyboard. If it was plugged in on the old branch than the broken values stick

**Comment by ids1024** [comment]
> On old or new firmware?

Should be an issue on either. You're changing the strings used to represent keycodes in `layouts.py`. This needs to match `layouts/picker.json`, and is also used in layout export, so changing these will break import of existing layout exports.

> You will have to re-flash firmware on your keyboard. If it was plugged in on the old commit version than the broken values stick

This is after reverting the layout to defaults on an older version of the Configurator.

**Comment by leviport** [comment]
With firmware from the [rebase](https://github.com/system76/qmk_firmware/pull/34) this seems like it's mostly working. There are just a few keys that are showing up a bit weird, and they aren't showing up weird the same time every time I launch the configurator or unplug and re-plug Heavy






From what I can tell, these are the ones that are sometimes showing up weird:
- Reset/Unlock: showing up as `BOOT`
- Media Previous: showing up as `MPRV`
- Media Next: showing up as `MNXT`
- Numpad Slash: showing up as `PSLS`
- Numpad minus: showing up as `PMNS`
- Numpad plus: showing up as `PPLS`
- Numpad enter: showing up as `PENT`
- Numpad period: showing up as `PDOT`
- Numpad asterisk: showing up as `PAST`
- Num Lock: showing up as `NUM`
- Bksp: showing up as `BACKSPACE`
- Right alt: showing up as `ALGR`
- Right arrow: showing up as `RGHT`

This list might not get everything, but I'll update it if I catch any more.

Since some of them are different each time the keyboard is detected, I think there's some race condition stuff happening.

**Comment by ids1024** [comment]
> Since some of them are different each time the keyboard is detected, I think there's some race condition stuff happening.

Luckily it's not a race, and just non-deterministic hashing. If `keymap.json` maps multiple names to the same number.

Looks like there are fewer but that's still an issue. Here's a script to test that:

```python3
#!/usr/bin/env python3

import json
import pprint
import sys

def duplicates(l):
    d = {}
    for k, v in l:
        if v in d:
            d[v].append(k)
        else:
            d[v] = [k]
    return {k:v for k,v in d.items() if len(v) > 1}

path = sys.argv[1]
file = open(path)
output = json.load(file, object_pairs_hook=duplicates)
pprint.pprint(output)
```

Not an issue I thought of before, but something we should have a unit test for. There are already some other tests to validate correctness of `layouts`.

Otherwise, this is generally looking reasonable. Once we make sure the `keymap.json` files are all correct.

**Comment by leviport** [comment]
Now on firmware from the [rebase](https://github.com/system76/qmk_firmware/pull/34), I'm no longer seeing unlabeled or strangely labeled keys while testing on Heavy. I'll keep an eye out, in case any others need to be added to the list, but it's definitely much better than it was.

On firmware currently in `master` of our QMK firmware, the layer toggle and access keys are still showing up blank in the configurator. If I remap the Access keys with the configurator, they are labeled correctly afterwards, but they act like toggle keys instead. So "Access layer 3" gets me stuck on layer 3 until I re-toggle layer 1 again.

**Comment by 13r0ck** [comment]
@leviport @ids1024 hows this looking now?

**Comment by ids1024** [comment]
There are still some duplicates in `keymap.json` files as tested with the script above.

**Comment by ids1024** [comment]
Need to unit test that, and update the unit tests to test with before "legacy scancodes" and the new ones.

**Comment by 13r0ck** [comment]
> There are still some duplicates in keymap.json files as tested with the script above.

Where? I don't see any duplicated when I run it

**Comment by ids1024** [comment]
Running it on `overrides/0.19.12` files like `./layouts/keyboards/overrides/0.19.12/system76/launch_1/keymap.json`:

```python
{0: ['NONE', 'BASIC'],
 71: ['SCROLL_LOCK', 'SCRL', 'BRMD'],
 72: ['PAUSE', 'PAUS', 'BRK', 'BRMU'],
 73: ['INSERT', 'INS'],
 100: ['NONUS_BACKSLASH', 'NUBS'],
 103: ['NUM_EQUALS', 'PEQL'],
 116: ['EXECUTE', 'EXEC'],
 119: ['SELECT', 'SLCT'],
 121: ['AGAIN', 'AGIN'],
 125: ['PASTE', 'PSTE'],
 130: ['LOCKING_CAPS_LOCK', 'LCAP'],
 131: ['LOCKING_NUM_LOCK', 'LNUM'],
 132: ['LOCKING_SCROLL_LOCK', 'LSCR'],
 133: ['NUM_COMMA', 'PCMM'],
 135: ['INTERNATIONAL_1', 'INT1'],
 136: ['INTERNATIONAL_2', 'INT2'],
 137: ['INTERNATIONAL_3', 'INT3'],
 138: ['INTERNATIONAL_4', 'INT4'],
 139: ['INTERNATIONAL_5', 'INT5'],
 140: ['INTERNATIONAL_6', 'INT6'],
 141: ['INTERNATIONAL_7', 'INT7'],
 142: ['INTERNATIONAL_8', 'INT8'],
 143: ['INTERNATIONAL_9', 'INT9'],
 144: ['LANGUAGE_1', 'LNG1'],
 145: ['LANGUAGE_2', 'LNG2'],
 146: ['LANGUAGE_3', 'LNG3'],
 147: ['LANGUAGE_4', 'LNG4'],
 148: ['LANGUAGE_5', 'LNG5'],
 149: ['LANGUAGE_6', 'LNG6'],
 150: ['LANGUAGE_7', 'LNG7'],
 151: ['LANGUAGE_8', 'LNG8'],
 152: ['LANGUAGE_9', 'LNG9'],
 153: ['ALTERNATE_ERASE', 'ERAS'],
 154: ['SYSTEM_REQUEST', 'SYRQ'],
 155: ['CANCEL', 'CNCL'],
 156: ['CLEAR', 'CLR'],
 157: ['PRIOR', 'PRIR'],
 158: ['RETURN', 'RETN'],
 159: ['SEPARATOR', 'SEPR'],
 162: ['CLEAR_AGAIN', 'CLAG'],
 163: ['CRSEL', 'CRSL'],
 164: ['EXSEL', 'EXSL'],
 165: ['SYSTEM_POWER', 'PWR'],
 166: ['SUSPEND', 'SLEP'],
 167: ['SYSTEM_WAKE', 'WAKE'],
 173: ['MEDIA_STOP', 'MSTP'],
 175: ['MEDIA_SELECT', 'MSEL'],
 176: ['MEDIA_EJECT', 'EJCT'],
 178: ['CALCULATOR', 'CALC'],
 179: ['MY_COMPUTER', 'MYCM'],
 180: ['WWW_SEARCH', 'WSCH'],
 181: ['WWW_HOME', 'WHOM'],
 182: ['WWW_BACK', 'WBAK'],
 183: ['WWW_FORWARD', 'WFWD'],
 184: ['WWW_STOP', 'WSTP'],
 185: ['WWW_REFRESH', 'WREF'],
 186: ['WWW_FAVORITES', 'WFAV'],
 187: ['MEDIA_FAST_FORWARD', 'MFFD'],
 188: ['MEDIA_REWIND', 'MRWD'],
 189: ['BRIGHTNESS_UP', 'BRIU'],
 190: ['BRIGHTNESS_DOWN', 'BRID'],
 191: ['CONTROL_PANEL', 'CPNL'],
 192: ['ASSISTANT', 'ASST'],
 205: ['MS_UP', 'MS_U'],
 206: ['MS_DOWN', 'MS_D'],
 207: ['MS_LEFT', 'MS_L'],
 208: ['MS_RIGHT', 'MS_R'],
 209: ['MS_BTN1', 'BTN1'],
 210: ['MS_BTN2', 'BTN2'],
 211: ['MS_BTN3', 'BTN3'],
 212: ['MS_BTN4', 'BTN4'],
 213: ['MS_BTN5', 'BTN5'],
 214: ['MS_BTN6', 'BTN6'],
 215: ['MS_BTN7', 'BTN7'],
 216: ['MS_BTN8', 'BTN8'],
 217: ['MS_WH_UP', 'WH_U'],
 218: ['MS_WH_DOWN', 'WH_D'],
 219: ['MS_WH_LEFT', 'WH_L'],
 220: ['MS_WH_RIGHT', 'WH_R'],
 221: ['MS_ACCEL0', 'ACL0'],
 222: ['MS_ACCEL1', 'ACL1'],
 223: ['MS_ACCEL2', 'ACL2'],
 21024: ['MOMENTARY', 'LAYER_ACCESS_1'],
 21088: ['TOGGLE_LAYER', 'LAYER_TOGGLE_1'],
 28928: ['MIDI', 'MIDI_ON'],
 29696: ['JOYSTICK', 'JOYSTICK_BUTTON_0'],
 29760: ['PROGRAMMABLE_BUTTON', 'PROGRAMMABLE_BUTTON_1'],
 29824: ['AUDIO', 'AUDIO_ON'],
 30464: ['MACRO', 'MACRO_0'],
 30720: ['LIGHTING', 'BACKLIGHT_ON'],
 30753: ['RGB_MODE_FORWARD', 'RGB_MOD'],
 30754: ['RGB_MODE_REVERSE', 'RGB_RMOD'],
 30763: ['RGB_MODE_PLAIN', 'RGB_M_P'],
 30764: ['RGB_MODE_BREATHE', 'RGB_M_B'],
 30765: ['RGB_MODE_RAINBOW', 'RGB_M_R'],
 30766: ['RGB_MODE_SWIRL', 'RGB_M_SW'],
 30767: ['RGB_MODE_SNAKE', 'RGB_M_SN'],
 30768: ['RGB_MODE_KNIGHT', 'RGB_M_K'],
 30769: ['RGB_MODE_XMAS', 'RGB_M_X'],
 30770: ['RGB_MODE_GRADIENT', 'RGB_M_G'],
 30771: ['RGB_MODE_RGBTEST', 'RGB_M_T'],
 30772: ['RGB_MODE_TWINKLE', 'RGB_M_TW'],
 31745: ['REBOOT', 'RBT'],
 31766: ['GRAVE_ESCAPE', 'GESC'],
 31832: ['LEADER', 'LEAD']}
```

**Comment by 13r0ck** [comment]
Ah thanks, fixed.

> We need to unit test that,

I think [un-commenting this](https://github.com/pop-os/keyboard-configurator/pull/164/commits/ec4b251c9e5393a2aa84833ddf11aa47698fc193#diff-3a397beef4087d4374331528ee685b961f222bf6037cd64203e4e1fe7bb71f0dL262) is probably good enough

**Comment by ids1024** [comment]
Ah right, so that's where I had a test for that. Though there are still a few unit tests in `backend/src/layout/mod.rs` that are passing `"dummy"` as the `version` to `Layout::from_board`, and should probably be written to test both versions.

**Comment by ids1024** [comment]
There seem to be some differences in the names being used in `overrides/0.19.12/*/keymap.json` and `*/keymap.json` 

`layouts/keyboards/system76/launch_1/keymap.json` uses `INT1` while `layouts/keyboards/overrides/0.19.12/system76/launch_1/keymap.json` uses `INTERNATIONAL_1`. Even if we don't currently show those in the UI, these should bve consistent. Why are those added to `QMK_MAPPING`?

It would be good to make sure both versions of `keymap.json` are generated with the same exact version of `layouts.py` (on different version of QMK) and that the old version hasn't changed.

**Comment by 13r0ck** [comment]
> It would be good to make sure both versions of keymap.json are generated with the same exact version of layouts.py 

We can't do that. The file locations and keymaps have changed altogether.

> Why are those added to `QMK_MAPPING`

They were one of the duplicates from above. QMK added a ton of ailases. So if we can only have one name in the keyboard configurator, then we need to map the alias names to the names we want to use in the keyboard configurator as well.

> Though there are still a few unit tests in backend/src/layout/mod.rs that are passing "dummy" 

They now use the the version number 3909300ea213ea2cdb6e63a7546c107de2fcb742

**Comment by ids1024** [comment]
I've added a commit that makes sure the same names are used for scancodes as previous, fixes some other things in `layouts.py`, and re-generates everything. I think it should be correct now. Though some details of how things are handled could be cleaned up more in the future.

**Comment by ids1024** [comment]
It's already a bit awkward how the scancodes are duplicated multiple times when all EC boards are the same ones and all QMK boards use the same ones. And then there's https://github.com/pop-os/keyboard-configurator/issues/139. So that's something to improve later but not a blocker here.

**Comment by 13r0ck** [comment]
@leviport 
Please QA #166 first. They I can rebase on that, then we can QA this.

**Comment by 13r0ck** [comment]
@leviport #166 has been merged, and this has been rebased and is ready for review.

**Comment by 13r0ck** [comment]
@ids1024
After QA-ing this with @leviport it seems like your commit broke this. Would you like to keep working on this, or just drop that commit?

**Comment by 13r0ck** [comment]
@leviport can add more details

**Comment by ids1024** [comment]
It would be best to keep those changes and fix whatever the issue is. What did it break?

**Comment by leviport** [comment]
It's kinda the same thing that was happening on our `master` branch of QMK earlier, but now it's happening on the rebase:


The layer keys are showing up blank, and they do not work right if I map them manually.

**Comment by ids1024** [comment]
Hm, my commit doesn't change `FN` in any way, so that shouldn't be impacted by it. Is a different commit here the issue?

What is the right half of the spacebar bound to there? Presumably not space, or it's particularly strange.

**Comment by leviport** [comment]
Sorry, here's the mapping:
L1:

L3:


Those screenshots were taken with the Lite flashed from QMK `master`, and everything is showing up correctly. Here's L3 with the QMK rebase firmware, for comparison:


The toggle layer keys are also blank, as well as my reset key. On the default keymap, access layer 2 is doing the same thing, so I think it's all the layer keys.

**Comment by ids1024** [comment]
Ah, so that should be "Access Layer 3".

Regardless, https://github.com/pop-os/keyboard-configurator/pull/164/commits/6536c5b3dc3fd935b249ea85ad9b82412c63da63 doesn't change the name or numeric value for any of the layer scancodes, so it shouldn't be the issue...

**Comment by leviport** [comment]
It's reproducible on the default maps as well as my own map on launch_1, launch_lite_1, and launch_heavy_1. It's probably the same on launch_2, I just don't have one handy. Current QMK `master` was working, then flashing the rebased firmware results in blank layer keys.

**Comment by ids1024** [comment]
Is this building QMK from a clean source tree? I see something similar, but the version is being reported wrong by the keyboard. Removing an old `./quantum/version.h` file (which is in `.gitignore`, but also wasn't removed by `make distclean`). After removing that it seems the generated `./.build/obj_system76_launch_1_default/src/version.h` is being used and the Configurator works as expected.

**Comment by leviport** [comment]
It's a pretty fresh clone, but I don't remember for sure whether or not I ever had the rebase branch checked out, so I'll re-clone it and try again soon

**Comment by ids1024** [comment]
Just removing the old `quantum/version.h` should fix it if this is the issue. And I guess a `make distclean` to make sure everything is rebuilt.

**Comment by leviport** [comment]
Sorry I didn't get to this sooner, but I can confirm that freshly cloning QMK and flashing `master` has working layer keys in the configurator. I'm going to do a little more testing before approving, but this might be good to go now.

**Review by leviport — APPROVED** [review]
This is also working on the rebase. Tested with launch_heavy_1, launch_lite_1, and launch_1, both with the 0.19.12 rebase firmware, and with firmware in current QMK `master`.

**Review by ids1024 — APPROVED** [review]
Everything here should be correct now.

**Pull request merged**
