### PR TITLE
Add launch_3 and launch_heavy_3

### PR DESCRIPTION
**Pull request by jackpot51**
I'm not sure if this has everything required, but it works to show these boards in the configurator. Please do a thorough review.

### CODE REVIEW

**Review by ids1024 — DISMISSED** [review]
`meta.json` files seem to be correct, other files match `launch_1`/`launch_2` and `launch_heavy_1` as expected.

I've been meaning to de-duplicate things here so the same `keymap.json` files could be shared by all QMK boards and all EC boards, and `launch_1`/`launch_2`/`launch_3` could have the same files in `keyboards` (which should also help with https://github.com/pop-os/keyboard-configurator/issues/139).

But this is right for how things currently work, assuming testing goes as expected.

**Comment by jackpot51** [comment]
@pop-os/quality-assurance any thoughts on this?

**Comment by leviport** [comment]
Somehow I missed this, sorry about that. I'll look at it today.

**Comment by ids1024** [comment]
This will need to be updated slightly for the changes in https://github.com/pop-os/keyboard-configurator/pull/208. I can do that.

**Comment by jackpot51** [comment]
That would be helpful, @ids1024. Thanks @leviport

**Comment by ids1024** [comment]
Okay, rebased, added the `is_qmk` field to `meta.json`, regenerated with `layouts.py`, and removed the files that are no longer needed.

`layouts.py` didn't change anything except `layouts/keyboards/system76/launch_heavy_3/leds.json`. Looks like the LED mapping has issues though. But it's different than `launch_heavy_1`, so I'm not sure exactly what would be correct: https://github.com/system76/qmk_firmware/pull/35#issuecomment-1662847545.

**Comment by ids1024** [comment]
Updated https://github.com/system76/qmk_firmware/pull/35 and this to use LED mapping that should be correct.

**Comment by leviport** [comment]
I'm not sure if it's because of this PR or the firmware itself, but setting LEDs is not persistent across unplug/replugs. I can set the LEDs differently, but unplugging the keyboard and plugging it back in results in the default Spacetime LED pattern. Key binding changes still persist as expected, however.

**Comment by jackpot51** [comment]
@leviport that would be firmware.

**Review by leviport — APPROVED** [review]
Since the LED bug is due to firmware, I think this update is good to go. `--launch-test` mode is working, keymap importing/exporting is working, and I can assign keys and LEDs on launch_3 and launch_heavy_3. Quick regression testing on launch_lite_1, launch_1, and my oryp9's bulit-in keyboard also went smoothly.

**Comment by jackpot51** [comment]
@ids1024 can you do an engineering review?

**Review by ids1024 — APPROVED** [review]

**Pull request merged**
